version: "2"

linters:
  default: standard
  enable:
    - misspell
    - revive
  settings:
    misspell:
      locale: UK
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
